#!/usr/bin/python

import sys
import gnsq
import json

if len(sys.argv) < 4:
    sys.stderr.write("Invalid number of arguments\n")
    sys.stderr.write("Usage: %s base_repo base_commit patch...\n" % sys.argv[0])
    sys.exit(1)

base_repo = sys.argv[1]
base_commit = sys.argv[2]
patch_list = sys.argv[3:]

conn = gnsq.Nsqd(address='localhost', http_port=4151)

conn.publish(
    'series_discovered',
    json.dumps({'base_repo': base_repo,
                'base_commit': base_commit,
                'patch_list': patch_list}))
