#!/usr/bin/python

import sys
import gnsq
import json
import logging

if len(sys.argv) != 1:
    sys.stderr.write("Invalid number of arguments\n")
    sys.stderr.write("Usage: %s\n" % sys.argv[0])
    sys.exit(1)

logging.basicConfig()
logger = logging.getLogger('logger')
conn = gnsq.Nsqd(address='localhost', http_port=4151)

reader = gnsq.Reader('series_built', 'test', 'localhost:4150')

@reader.on_message.connect
def handler(reader, message):
    series = json.loads(message.body)
    if series['build_success']:
        if "broken" in series['patch_list']:
            series['test_success'] = False
            series['test_log'] = "CPU burned down"
        else:
            series['test_success'] = True
        conn.publish('series_tested', json.dumps(series))
    message.finish()

reader.start()
